### ISSUE TITLE
Can't Build on Ubuntu 12.04 x86_64

### ISSUE THREAD

**Issue by onionjake** [boyski/audited-objects#1]
```
$ make
cd src && make -s rt TGTARCH=
OS_CPU=Linux_x86_64
aotool.c: In function ‘_name_pathstate’:
aotool.c:160:19: error: storage size of ‘stbuf’ isn’t known
aotool.c:166:5: error: implicit declaration of function ‘stat64’ [-Werror=implicit-function-declaration]
aotool.c:160:19: error: unused variable ‘stbuf’ [-Werror=unused-variable]
aotool.c: In function ‘do_action’:
aotool.c:365:22: error: storage size of ‘stbuf’ isn’t known
aotool.c:375:3: error: implicit declaration of function ‘lstat64’ [-Werror=implicit-function-declaration]
aotool.c:365:22: error: unused variable ‘stbuf’ [-Werror=unused-variable]
cc1: all warnings being treated as errors
make[1]: *** [aotool.o] Error 1
make: *** [java/WebContent/client/ao--3.8.0-29-generic.tar.gz] Error 2
```
